---
title: "TEACHING"
---

---

<h3>**TEACHING PHILOSOPHY**</h3>

<font size="4">As a first-generation college student, I embarked on a journey of learning and discovery, starting humbly at Ventura Community College, advancing through the halls of UC Santa Barbara, and culminating in achieving my Ph.D. from UC Irvine. This path wasn't just a series of academic milestones; it was a voyage through diverse worlds of thought, scholarship, and experience, leading me through the realms of higher education and into the depths of personal growth and understanding.

In the classrooms where I now stand, I see reflections of my own journey in my students' eyes. These diverse, eager minds come from all walks of life, each with a unique story. I remember the challenges I faced and the barriers I overcame, and it fuels my commitment to them. Through mentorship, I don't just teach; I connect, understand, and help pave their roads to success in academia and beyond.

My approach to teaching is like crafting a mosaic, where each student's piece is vital to the whole picture. I bring the vibrancy of active learning to our space, ensuring that every voice is heard and valued. In our inclusive, equitable environment, learning isn't just about facts and theories; it's a dance of ideas, cultures, and perspectives. As a Latino educator, I weave the threads of diversity, equity, and inclusion into the fabric of our curriculum. It's not just a policy; it's a lived experience, a testament to the richness that different backgrounds bring to our collective learning.

But my role extends beyond the classroom. I strive to light a fire in each student, empowering them to apply their sociological insights to real-world challenges. Guiding them through the intricacies of research, I help them find their voice, articulate their thoughts, and project their ideas onto larger canvases. In doing so, I am not just teaching but cultivating future leaders, thinkers, and change-makers.

As I stand before my students, I see not just faces in a crowd but the future architects of society. They will advocate for change, define their destinies, and, in turn, light the way for others. It's in this journey of empowerment and transformation that I find my purpose, ready to contribute to the rich tapestry of our sociology program and to guide these bright minds towards a world of possibilities in criminal justice, law, social services, complex organizations, and the noble field of teaching.</font>

----

<h2>**PROFESSIONAL EXPERIENCE**</h2>

<h3>**Instructor**</h3>

### California State University, Chico - 2022-Present

  * <font size="2.5">Contemporary Social Theory (in-person, online)
  * Classical Social Theory (in-person, online)
  * Global Problems (online)
  * Global Perspectives on Ethnicity and Nationality (online)
  * Food Justice (online)
  * Sociology of Gangs (online) 
  </font>

### California State University, Long Beach - 2021-2022
  
  * <font size="2.5">Modern Sociological Theory (in-person)
  * Global Conflict and Resolution (in-person)
  * Global Sociology (in-person)
  * Elementary Statistics (in-person and online)
  </font>
  
### California State University, Dominguez Hills - 2018-2021

  * <font size="2.5">Global Organizations and Social Processes (in-person)
  * Globalization: Theory and Research (in-person)
  
  </font>
  
### University of California, Irvine - 2019-2020

  * <font size="2.5">Sociology/Anthropology 10B: Statistics and Probability, II (online) 
  * Statistics Bootcamp Refresher (in-person, online)
  </font>

<h3>**Teaching Assistant**</h3>

### University of California, Irvine - 2016-2022

  * <font size="2.5">Graduate Statistics for Sociology and Demographic Analysis, I, II, III
  * Statistics for Sociology, I, II, III
  * Sociology of Birth, Death & Migration
  * Sociological Theory
  * Introduction to Sociology
  </font>
  
### University of California, Santa Barbara

  * <font size="2.5">Beginning Spanish, I
  * Beginning Spanish, II
  * Latin American and Iberian Studies
  </font>

----

<h3>**PEDAGOGICAL DEVELOPMENT**</h3>

<h4>**Pedagogical Fellow - 2019-2020**</h4>

 * <font size="2.5">Facilitated interactive workshops designed to provide new Teaching Assistants (TAs) with skills and information that helped them jumpstart their teaching careers at the UC Irvine.</font>

* Assessed other fellows’ teaching performance by conducting in-class observation of their teaching then provided one-on-one consultation and feedback.

* Worked with department director on developing an application and selection process of new Pedagogical Fellows that protected against selection bias, created an inclusive experience, and streamlined an effective interviewing process.


<h4>**Division of Teaching Excellence and Innovation (DTEI) Summer Fellows Program Coordinator - 2020-2021**</h4>

* <font size="2.5">Supported the university in fast-tracking the development of a pedagogical training program that prepares faculty and graduate students to effectively transition to online remote instruction.

* Managed and supervised the pedagogical training of 50 fellows and faculty from various disciplines across different areas such as STEM, Social Sciences, Humanities and the Arts.
</font>

---

<p>Copyright &copy; `r format(Sys.Date(), '%Y')` Martín Jacinto. All rights reserved.</p>




